# stiPrEP burnin analysis
## Process burn-in
library("EpiModelHPC")
library("EpiModelHIV")
rm(list=ls())

list.files("data/")
unlink("data/sim.*")
system("scp hyak:/gscratch/csde/sjenness/sti/data/sim.n300.rda scripts/burnin/data/")
load("scripts/burnin/data/sim.n300.rda")

ls()

ir100.gc <- as.numeric(sim$epi$ir100.gc[2600, ])
round(quantile(ir100.gc, probs = c(0.025, 0.5, 0.975)), 3)

ir100.ct <- as.numeric(sim$epi$ir100.ct[2600, ])
round(quantile(ir100.ct, probs = c(0.025, 0.5, 0.975)), 3)

i.prev <- as.numeric(sim$epi$i.prev[2600, ])
round(quantile(i.prev, probs = c(0.025, 0.5, 0.975)), 3)

#prev.rgcct <- as.numeric(sim$epi$prev.rgcct[2600, ])
#round(quantile(prev.rgcct, probs = c(0.025, 0.5, 0.975)), 3)

#prev.ugcct <- as.numeric(sim$epi$prev.ugcct[2600, ])
#round(quantile(prev.ugcct, probs = c(0.025, 0.5, 0.975)), 3)

ir100 <- as.numeric(sim$epi$ir100[2600, ])
round(quantile(ir100, probs = c(0.025, 0.5, 0.975)), 3)

ir100syph <- as.numeric(sim$epi$ir100.syph[2600, ])
round(quantile(ir100syph, probs = c (0.025, 0.5, 0.975)), 3)

prev.syph.hivpos <- as.numeric(sim$epi$prev.syph.hivpos[2600, ])
round(quantile(prev.syph.hivpos, probs = c(0.025, 0.5, 0.975)), 3)

prev.syph.hivneg <- as.numeric(sim$epi$prev.syph.hivneg[2600, ])
round(quantile(prev.syph.hivneg, probs = c(0.025, 0.5, 0.975)), 3)

syphratio <- as.numeric(prev.syph.hivpos/prev.syph.hivneg)
round(quantile(syphratio, probs = c(0.025, 0.5, 0.975)), 3)

# Summary of 500 sims
par(mfrow = c(3,2), oma=c(0,0,2,0))
plot(sim, y = "i.prev", ylim = c(0.23, 0.29))
title("HIV Prevalence")
abline(h=0.26, col = "red", lty = 2)
#plot(sim, y = "prev.rgcct", ylim = c(0.12, 0.17))
#title("Rectal STI Prevalence")
#plot(sim, y = "prev.ugcct", ylim = c(0.06, 0.11))
#title("Urethral STI Prevalence")
plot(sim, y = "ir100.gc", ylim = c(0, 8))
title("Gonococcal Incidence Rate")
abline(h=4.2, col = "red", lty = 2)
plot(sim, y = "ir100.ct", ylim = c(0, 8))
title("Chlamydial Incidence Rate")
abline(h=6.6, col = "red", lty = 2)
plot(sim, y = "ir100", ylim = c(3, 5))
title("HIV Incidence Rate")
abline(h=3.8, col = "red", lty = 2)
plot(sim, y = "ir100.syph", ylim = c(0, 3))
title("Syphilis Incidence Rate")
abline(h=0.9, col = "red", lty = 2)
#plot(sim, y = "prev.syph.hivpos", ylim = c(0, 0.15))
# title("Syphilis prevalence in HIV+")
# abline(h=0.103, col = "red", lty = 2)
# plot(sim, y = "prev.syph.hivneg", ylim = c(0, 0.08))
# title("Syphilis prevalence in HIV-")
# abline(h=0.026, col = "red", lty = 2)
#plot(sim, y = ("prev.syph.hivpos" / "prev.syph.hivneg"), ylim = c(0, 6))
#title("Syphilis Prevalence Ratio by HIV status")
#abline(h=3.96, col = "red", lty = 2)
title(main="Statistics for 500 Simulations", outer=TRUE)

# Synergy plots
par(mfrow=c(2,3), oma=c(0,0,2,0))
plot(sim, y = "prev.syph.hivpos", ylab = "Prevalence", ylim=c(0, 0.12))
plot(sim, y = "prev.syph.hivneg", ylab = "Prevalence", add = TRUE)
abline(h = 0.103, col = "red", lty = 2)
abline(h = 0.026, col = "red", lty = 2)
title("Syphilis by HIV Status")
plot(sim, y = "prev.gc.hivpos", ylab = "Prevalence")
plot(sim, y = "prev.gc.hivneg", ylab = "Prevalence", add = TRUE)
title("GC by HIV Status")
plot(sim, y = "prev.ct.hivpos", ylab = "Prevalence")
plot(sim, y = "prev.ct.hivneg", ylab = "Prevalence", add = TRUE)
title("CT by HIV Status")
plot(sim, y = "prev.hiv.syphpos", ylab = "Prevalence")
plot(sim, y = "prev.hiv.syphneg", ylab = "Prevalence", add = TRUE)
title("HIV by Syphilis +/-")
plot(sim, y = "prev.hiv.gcpos", ylab = "Prevalence")
plot(sim, y = "prev.hiv.gcneg", ylab = "Prevalence", add = TRUE)
title("HIV by GC +/-")
plot(sim, y = "prev.hiv.ctpos", ylab = "Prevalence")
plot(sim, y = "prev.hiv.ctneg", ylab = "Prevalence", add = TRUE)
title("HIV by CT +/-")
title("Syph Tprob = XXX, Syph.HIV.RR = , HIV.Syph.RR =", outer = TRUE)


# Summary of mean simulation
# Run after burnin.process
par(mfrow = c(3,3), oma=c(0,0,2,0))
plot(sim, y = "i.prev", ylim = c(0.23, 0.29))
title("HIV Prevalence")
abline(h=0.26, col = "red", lty = 2)
#plot(sim, y = "prev.rgcct", ylim = c(0.12, 0.17))
#title("Rectal STI Prevalence")
#plot(sim, y = "prev.ugcct", ylim = c(0.06, 0.11))
#title("Urethral STI Prevalence")
plot(sim, y = "ir100.gc", ylim = c(0, 8))
title("Gonococcal Incidence Rate")
abline(h=4.2, col = "red", lty = 2)
plot(sim, y = "ir100.ct", ylim = c(0, 8))
title("Chlamydial Incidence Rate")
abline(h=6.6, col = "red", lty = 2)
plot(sim, y = "ir100", ylim = c(3, 5))
title("HIV Incidence Rate")
abline(h=3.8, col = "red", lty = 2)
plot(sim, y = "ir100.syph", ylim = c(0, 3))
title("Syphilis Incidence Rate")
abline(h=0.9, col = "red", lty = 2)
plot(sim, y = "prev.syph.hivpos", ylim = c(0, 0.15))
title("Syphilis prevalence in HIV+")
abline(h=0.103, col = "red", lty = 2)
plot(sim, y = "prev.syph.hivneg", ylim = c(0, 0.08))
title("Syphilis prevalence in HIV-")
abline(h=0.026, col = "red", lty = 2)
title(main="Statistics for 500 Simulations", outer=TRUE)
plot(sim, y = "syphratio", ylim = c(0, 6))
title("Ratio of Syphilis prevalence by HIV status")
abline(h=3.96, col = "red", lty = 2)
title(main="Statistics for best-fitting simulation", outer=TRUE)


df <- as.data.frame(sim)
head(df$prev.rgcct, 100)

plot(sim, y = "prev.rgcct", mean.smooth = FALSE)

df <- tail(as.data.frame(sim), 500)
sum(df$trans.main) / sum(df$incid)
sum(df$trans.casl) / sum(df$incid)
sum(df$trans.inst) / sum(df$incid)

sum(df$trans.main.gc) / sum(df$incid.gc)
sum(df$trans.casl.gc) / sum(df$incid.gc)
sum(df$trans.inst.gc) / sum(df$incid.gc)

sum(df$trans.main.ct) / sum(df$incid.ct)
sum(df$trans.casl.ct) / sum(df$incid.ct)
sum(df$trans.inst.ct) / sum(df$incid.ct)
